require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  # DisabledByDefault: true
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "db/schema.rb"
    - "config/puma.rb"
    - "config/initializers/backtrace_silencers.rb"
    - "config/initializers/content_security_policy.rb"
    - "config/environments/production.rb"

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Metrics/BlockLength:
  AllowedMethods: ["context"]
  Exclude:
    - "config/environments/development.rb"
    - "config/routes.rb"
